# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up

version: '3.3'

services:
  vpn-26:
    image: cloud.canister.io:5000/skr/skr-openvpn-server:tunnel
    cap_add:
      - NET_ADMIN
    ports:
      - "2226:22"
      - "1195:1194/udp"
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-26:/opt/Dockovpn_data
    restart: always

  vpn-73:
    image: cloud.canister.io:5000/skr/skr-openvpn-server:tunnel
    cap_add:
      - NET_ADMIN
    ports:
      - "2273:22"
      - "1196:1194/udp"
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-73:/opt/Dockovpn_data
    restart: always

  vpn-68:
    image: cloud.canister.io:5000/skr/skr-openvpn-server:tunnel
    cap_add:
      - NET_ADMIN
    ports:
      - "2268:22"
      - "1197:1194/udp"
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-68:/opt/Dockovpn_data
    restart: always

#  vpn-44:
#    image: cloud.canister.io:5000/skr/skr-openvpn-server:tunnel
#    cap_add:
#      - NET_ADMIN
#    ports:
#      - "2244:22"
#      - "1198:1194/udp"
#    environment:
#      HOST_ADDR: ${HOST_ADDR}
#    volumes:
#      - openvpn-44:/opt/Dockovpn_data
#    restart: always

  vpn-56:
    image: cloud.canister.io:5000/skr/skr-openvpn-server:tunnel
    cap_add:
      - NET_ADMIN
    ports:
      - "2256:22"
      - "1199:1194/udp"
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-56:/opt/Dockovpn_data
    restart: always
  vpn-61:
    image: skr2/skr-openvpn-server
    cap_add:
      - NET_ADMIN
    ports:
      - 1193:1194/udp
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-61:/opt/Dockovpn_data
    restart: always

volumes:
  openvpn-26:
    external: true
  openvpn-73:
    external: true
  openvpn-68:
    external: true
  openvpn-44:
    external: true
  openvpn-56:
    external: true
  openvpn-61:
    external: true
