# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up

version: '3'
services:
  vpn-26:
    image: skr2/skr-openvpn-server
    cap_add:
      - NET_ADMIN
    ports:
      - 1195:1194/udp
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-26:/opt/Dockovpn_data
    restart: always
  vpn-73:
    image: skr2/skr-openvpn-server
    cap_add:
      - NET_ADMIN
    ports:
      - 1196:1194/udp
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - openvpn-73:/opt/Dockovpn_data
    restart: always

volumes:
  openvpn-26:
  openvpn-73:

